name: Multiple Jobs Workflow

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Print message from Job 1
        run: echo "This is Job 1"

  job2:
    runs-on: ubuntu-latest
    needs: job1  # Runs only after job1 completes
    steps:
      - name: Print message from Job 2
        run: echo "This is Job 2"
