name: Multiple Jobs Workflow

on: push

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Access secret
        run: echo "My secret is ${{ secrets.MY_SECRET_KEY }}"  # Will not print the actual value for security
